version: '3.3'
services:
  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    hostname: mariadb
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: Password-123!
      MYSQL_USER: mariaUser
      MYSQL_PASSWORD: Password-123!
      MYSQL_DATABASE: accounts
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
     - ./database/:/docker-entrypoint-initdb.d/

  webapp:
    build: ./web_application
    container_name: flask
    hostname: flask
    volumes:
      - ./web_application/static/videos:/app/static/videos
    ports:
      - '80:80'
